services:
  - type: web
    name: smart-storage-health-monitor
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
